# 'bundle exec jekyll serve' > Restart Server

# Variables
### in the templates using {{ site.myvariable }}.

# Author
author: Yosef
title: Yosef Tawil, aka thebeast353
description: >- 
  PenTester, Software Engineer / Full Stack Developer

# URLs
baseurl: "/"
url: "https://yoseftawil.github.io" 

# Defaults
permalink: /blog/:title/
layout: post
excerpt_separator: <!--end-->

# Twitter
twitter:
  url: https://twitter.com/yoseftawil
  username: yoseftawil

# GitHub
github:
  username:  yoseftawil
  url: https://github.com/yoseftawil/

# YouTube
youtube:
  username: DJ Kick
  url: https://www.youtube.com/channel/UCOqSvQ0fu4OhJ-Mlcrd5e-w

# Instagram
instagram:
  username: yoseftawil
  url: https://www.instagram.com/yoseftawil/

# Google Analytics
google_analytics: UA-175861539-1

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

