# 'bundle exec jekyll serve' > Restart Server

# Variables
### in the templates via {{ site.myvariable }}.

title: Yosef Tawil, aka thebeast353 # {{ site.title }}
email: sike@gotchu.com # {{ site.email }}
description: >- 
  PenTester, Software Engineer / Full Stack Developer

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yoseftawil
github_username:  yoseftawil

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
